/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lcgblog;
@org.apache.avro.specific.AvroGenerated
public enum Gender implements org.apache.avro.generic.GenericEnumSymbol<Gender> {
  MALE, FEMALE, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"com.lcgblog\",\"symbols\":[\"MALE\",\"FEMALE\",\"NONE\"],\"default\":\"NONE\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
